### ISSUE TITLE
How about migrating the tfplus and atorch as independent repositories?

### ISSUE THREAD

**Issue by mingcheng** [intelligent-machine-learning/dlrover#1358] opened 2024-11-27 02:11 UTC
FYI, I think the two libraries at the root of the project are very independent and transferable.

**Comment by antfin-oss** [comment] 2024-11-27 03:27
This is a huge PR #1359; it must be reviewed and confirmed before merging.

**Comment by antfin-oss** [comment] 2024-11-27 07:48
> This is a huge PR #1359; it must be reviewed and confirmed before merging.

I closed this pull request because it didn't pass the CI test. You can open PR again if everything is ready.

**Comment by mingcheng** [comment] 2024-11-27 08:06
> > This is a huge PR #1359; it must be reviewed and confirmed before merging.
> 
> I closed this pull request because it didn't pass the CI test. You can open PR again if everything is ready.

Generated the new pull request and passed the CI test. so it's ready to merge #1360

**Closed** 2024-11-28 07:26 UTC
Labels: help wanted, wip, dev issue
